name: reversi-actions
run-name: ${{ github.actor }} pushed
on: [push]
jobs:
    mypy:
        runs-on: ubuntu-latest
        name: Mypy
        steps:
        - uses: actions/checkout@v1
        - name: Set up Python 3.8
          uses: actions/setup-python@v1
          with:
              python-version: 3.8
        - name: Install Dependencies
          run: |
            pip install mypy
        - name: mypy src
          run: |
            mypy src/
        - name: mypy tests
          run: |
            mypy tests/
    pytest:
        runs-on: ubuntu-latest
        name: pytest
        steps:
        - uses: actions/checkout@v1
        - name: Set up Python 3.8
          uses: actions/setup-python@v1
          with:
              python-version: 3.8
        - name: Install Dependencies
          run: |
          pip install pytest
        - name: pytest
          run: |
          pytest /tests
