name: reversi-actions
on: [push]
jobs:
    check_files:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-python@v4
            with:
              python-version: 3.10
          - run: pip3 install -r requirements.txt
          - run: mypy src/* tests/*
          - run: pytest tests/*
            
